spring :
  application :
    name : smart-research-assistant
  ai:
    google:
      genai:
        api-key : ${GEMINI_KEY}
        chat:
          options:
            model : ${GEMINI_MODEL}

server :
  port : ${PORT:8080}


###for manual ai api integration
# gemini :
#   api :
#     url : https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=
#     key : ${GEMINI_KEY}


